services:
  - type: web
    name: rag-chatbot-backend
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        generateValue: true
      - key: NEON_DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false